version: '3'

services:
    database:
        container_name: guestbook-pgsql
        image: postgres:13-alpine
        volumes:
          - "./database:/var/lib/pgsql"
        restart: always
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: 
          - 5432:5432
